INSERT INTO category  (`id`, `name_en`, `name_ar`) VALUES
(1, "What to say before sleeping","أذكار النوم"),
(2, "Words of remembrance for morning and evening","أذكار الصباح والمساء"),
(3, "Invocation when getting dressed","دعاء ُلبْس الثوب"),
(4, "Invocation when putting on new clothes","دعاء ُلبْس الثوب الجديد"),
(5, "Invocations for someone who has put on new clothes","الدعاء لمن لبس ثوبا جديدا"),
(6, "What to say when undressing","ما يقول إذا وضع ثوبه"),
(7, "Invocation for entering the restroom","دعاء دخول الخلاء"),
(8, "Invocation for leaving the restroom","دعاء الخروج من الخلاء"),
(9, "What to say before performing ablution","الذكر قبل الوضوء"),
(10, "What to say upon completing ablution","الذكر بعد الفراغ من الوضوء"),
(11, "What to say when leaving the home","الذكر عند الخروج من المنزل"),
(12, "What to say when entering the home","الذكر عند دخول المنزل"),
(13, "Invocation for going to the mosque","دعاء الذهاب إلى المسجد"),
(14, "Invocation for entering the mosque","دعاء دخول المسجد"),
(15, "Invocation for leaving the mosque","دعاء الخروج من المسجد"),
(16, "What to say upon hearing the Athan (call to prayer)","أذكار الآذان"),
(17, "Invocations for the beginning of the prayer","دعاء الاستفتاح"),
(18, "Invocations during Ruki' (bowing in prayer)","دعاء الركوع"),
(19, "Invocations for rising from the Ruki'","دعاء الرفع من الركوع"),
(20, "Invocations during Sujood","دعاء السجود"),
(21, "Invocations for sitting between two prostrations","دعاء الجلسة بين السجدتين"),
(22, "Supplications for prostrating due to recitation of the Qur'an","دعاء سجود التلاوة"),
(23, "Invocation for At-Tashahhud (sitting in prayer)","التشهد"),
(24, "How to recite blessings on the Prophet after the Tashahhud","الصلاة على النبي بعد التشهد"),
(25, "Invocations after the final Tash-ahhud and before ending the prayer","الدعاء بعد التشهد الأخير قبل السلام"),
(26, "What to say after completing the prayer","الأذكار بعد السلام من الصلاة"),
(27, "Istikharah (seeking Allah's Counsel)","دعاء صلاة الاستخارة"),
(28, "supplications for when you wake up","أذكار الاستيقاظ من النوم"),
(29, "Invocation to say if you stir in the night","الدعاء إذا تقلب ليلا"),
(30, "What to say if you are afraid to go to sleep or feel lonely and depressed","دعاء الفزع في النوم و من بُلِيَ بالوحشة"),
(31, "What to do if you have a bad dream or nightmare","ما يفعل من رأى الرؤيا أو الحلم"),
(32, "Invocations for Qunut in the Witr prayer","دعاء قنوت الوتر"),
(33, "What to say immediately following the Witr prayer","الذكر عقب السلام من الوتر"),
(34, "Invocations in times of worry and grief","دعاء الهم والحزن"),
(35, "Invocations for anguish","دعاء الكرب"),
(36, "Invocations for when you meet an adversary or a powerful ruler.","دعاء لقاء العدو و ذي السلطان"),
(37, "Invocations against the oppression of rulers","دعاء من خاف ظلم السلطان"),
(38, "Invocation against an enemy","الدعاء على العدو"),
(39, "What to say if you fear people may harm you","ما يقول من خاف قوما"),
(40, "Invocations for if you are stricken by in your faith","دعاء من أصابه وسوسة في الإيمان"),
(41, "Invocations for the setting of a debt","دعاء قضاء الدين"),
(42, "Invocation against the distractions of Satan during the prayer and recitation of the Quran","دعاء الوسوسة في الصلاة و القراءة"),
(43, "Invocation for when you find something becoming difficult for you","دعاء من استصعب عليه أمر"),
(44, "What to say and do if you commit a sin","ما يقول ويفعل من أذنب ذنبا"),
(45, "Invocations against the Devil and his promptings","دعاء طرد الشيطان و وساوسه"),
(46, "Invocation for when something you dislike happens, or for when you fail to achieve what you attempt to do","الدعاء حينما يقع ما لا يرضاه أو ُ غلب على أمره"),
(47, "Congratulations for new parents and how they should respond","ﺗﻬنئة المولود له وجوابه"),
(48, "How to seek Allah's protection for children","ما يعوذ به الأولاد"),
(49, "Invocations for visiting the sick","الدعاء للمريض في عيادته"),
(50, "The reward for visiting the sick","فضل عيادة المريض"),
(51, "Invocations of the terminal ill","دعاء المريض الذي يئس من حياته"),
(52, "What to encourage the dying person to say","تلقين المحتضر"),
(53, "Invocation for when tragedy strikes","دعاء من أصيب بمصيبة"),
(54, "Invocation for closing the eyes of the dead","الدعاء عند إغماض الميت"),
(55, "Invocations for the dead in the Funeral prayer","الدعاء للميت في الصلاة عليه"),
(56, "Invocations for a child in the Funeral prayer","الدعاء للفرط في الصلاة عليه"),
(57, "Invocation for the bereaved","دعاء التعزية"),
(58, "Invocation to be recited when placing the dead in his grave","الدعاء عند إدخال الميت القبر"),
(59, "Invocation to be recited after burying the dead","الدعاء بعد دفن الميت"),
(60, "Invocation for visiting the graves","دعاء زيارة القبور"),
(61, "Invocations for when the wind blows","دعاء الريح"),
(62, "Invocation for when it thunder","دعاء الرعد"),
(63, "Some invocations for rain","من أدعية الاستسقاء"),
(64, "Invocation for when it rains","الدعاء إذا نزل المطر"),
(65, "Supplication after it rains","الذكر بعد نزول المطر"),
(66, "Invocation for the withholding of the rain","من أدعية الاستصحاء"),
(67, "Invocation for sighting the new moon","دعاء رؤية الهلال"),
(68, "Invocations for breaking the fast","الدعاء عند إفطار الصائم"),
(69, "Invocations before eating","الدعاء قبل الطعام"),
(70, "Invocations after eating","الدعاء عند الفراغ من الطعام"),
(71, "A dinner guest's invocation for his host","دعاء الضيف لصاحب الطعام"),
(72, "Invocation for someone who gives you drink or offers it to you","التعريض بالدعاء لطلب الطعام أو الشراب"),
(73, "Invocation for a family who invites you to break your fast with them","الدعاء إذا أفطر عند أهل بيت"),
(74, "Invocation for someone who offers you food when you are fasting, which you decline","دعاء الصائم إذا حضر الطعام ولم يفطر"),
(75, "What to say when you are fasting and someone is rude to you","ما يقول الصائم إذا سابه أحد"),
(76, "Invocation for when you see the first dates of the season","الدعاء عند رؤية باكورة الثمر"),
(77, "Invocation for sneezing","دعاء العطاس"),
(78, "What to say to the disbeliever if he sneezes and praises Allah","ما يقال للكافر إذا عطس فحمد الله"),
(79, "Invocation for the groom","الدعاء للمتزوج"),
(80, "The groom’s supplication on the wedding night or when buying an animal","دعاء المتزوج و شراء الدابة"),
(81, "Invocation to be recited before intercourse","الدعاء قبل إتيان الزوجة"),
(82, "Invocation for anger","دعاء الغضب"),
(83, "What to say if you see someone afflicted by misfortune","دعاء من رأى مبتلى"),
(84, "What to say while sitting in an assembly","ما يقال في اﻟﻤﺠلس"),
(85, "The Expiation of Assembly - Kaffaratul-Majlis","كفارة اﻟﻤﺠلس"),
(86, "vocation for someone who says: May Allah forgive you","الدعاء لمن قال غفر الله لك"),
(87, "Invocation for someone who does good to you","الدعاء لمن صنع إليك معروفا"),
(88, "Invocation for Allah's protection from the False Messiah","ما يعصم الله به من الدجال"),
(89, "Invocation for someone who tells you I love you for the sake of Allah","الدعاء لمن قال إني أحبك في الله"),
(90, "Invocation for someone who offers you a share of his wealth","الدعاء لمن عرض عليك ماله"),
(91, "Invocation (upon receipt of the loan) for someone who lends you money","الدعاء لمن أقرض عند القضاء"),
(92, "Invocation for fear of Shirk","دعاء الخوف من الشرك"),
(93, "Invocation for someone who tells you: May Allah bless you","الدعاء لمن قال بارك الله فيك"),
(94, "Invocation against evil portent","دعاء كراهية الطيرة"),
(95, "Invocation for riding in a vehicle or on an animal","دعاء الركوب"),
(96, "Invocation for traveling","دعاء السفر"),
(97, "Invocation for entering a town or city","دعاء دخول القرية أو البلدة"),
(98, "Invocation for entering a market","دعاء دخول السوق"),
(99, "Invocation for when your vehicle or mount begins to fail","الدعاء إذا تعس المركوب"),
(100, "The traveler's invocation for the one he leaves behind","دعاء المسافر للمقيم"),
(101, "The resident's invocations for the traveler","دعاء المقيم للمسافر"),
(102, "Glorifying and magnifying Allah on the journey","التكبير و التسبيح في سير السفر"),
(103, "The traveler's invocation at dawn","دعاء المسافر إذا أسحر"),
(104, "Invocation for a layover (stopping along the way) on the journey","الدعاء إذا نزل مترلا في سفر أو غيره"),
(105, "What to say upon returning from a Journey","ذكر الرجوع من السفر"),
(106, "What to say if something happens to please you or to displease you","ما يقول من أتاه أمر يسره أو يكرهه"),
(107, "The excellence of asking for Allah's blessings upon the Prophet pbuh","فضل الصلاة على النبي صلى الله عليه و سلم"),
(108, "spreading the greetings of Salam (Peace)","إفشاء السلام"),
(109, "How to reply to a disbeliever if he says Salam to you","كيف يرد السلام على الكافر إذا سلم"),
(110, "Invocation upon hearing the cock's crow or the bray of a donkey","الدُّعاءُ عِنْدَ سَمَاعِ صِياحِ الدِّيكِ ونَهِيقِ الْحِمَارِ"),
(111, "Invocation upon hearing a dog barking in the night","دعاء نباح الكلاب بالليل"),
(112, "Invocation for someone you have spoken ill to","الدعاء لمن سببته"),
(113, "How a Muslim should praise another Muslim","ما يقول المسلم إذا مدح المسلم"),
(114, "What a Muslim should say when he is praised","ما يقول المسلم إذا زكي"),
(115, "The pilgrim's announcement of his arrival for Hajj or Umrah","كيف يلبي المحرم في الحج أو العمرة ؟"),
(116, "Saying Allahu Akbar when passing the Black Stone","التكبير إذا أتى الركن الأسود"),
(117, "Invocation to be recited between the Yemenite Corner and the Black Stone","الدعاء بين الركن اليماني والحجر الأسود"),
(118, "Invocation to be recited while standing at Safa and Marwah","دعاء الوقوف على الصفا والمروة"),
(119, "Invocation to be recited on the Day of Arafat","الدعاء يوم عرفة"),
(120, "Supplication to be recited at the sacred area of Muzdalifah","الذكر عند المشعر الحرام"),
(121, "Saying Allahu Akbar while stoning the three pillars at Mina","التكبير عند رمي الجمار مع كل حصاة"),
(122, "What to say when surprised or startled","دعاء التعجب والأمر السار"),
(123, "What to say when something that pleases you happens","ما يفعل من أتاه أمر يسره"),
(124, "What to say when you feel a pain in your body","ما يقول من أحس وجعا في جسده"),
(125, "What to say when you fear you may afflict something with the evil eye","دعاء من خشي أن يصيب شيئا بعينه"),
(126, "What to say when you feel frightened","ما يقال عند الفزع"),
(127, "What to say when slaughtering or sacrificing an animal","ما يقول عند الذبح أو النحر"),
(128, "What to say to foil the devil's plots","ما يقول لرد كيد مردة الشياطين"),
(129, "Repentance and seeking forgiveness","الاستغفار و التوبة"),
(130, "The excellence of remembering Allah","فضل التسبيح و التحميد، و التهليل، و التكبير"),
(131, "How the Prophet glorified Allah","كيف كان النبي يسبح؟"),
(132, "Types of goodness and good etiquette for community life","من أنواع الخير والآداب الجامعة");
