INSERT INTO `quran_surah` (`id`, `name_ar`, `name_latin`, `name_en`, `name_fr`, `sajda`, `ayah`) VALUES
(1, 'سورة الفاتحة', 'Al-Fatiha', 'The Opening', 'L’ouverture', '0', 7),
(2, 'سورة البقرة', 'Al-Baqara', 'The Cow', 'La vache', '0', 286),
(3, 'سورة آل عمران', 'Aal-Imran', 'The family of Imran', 'La famille D’Imran', '0', 200),
(4, 'سورة النساء', 'An-Nisa', 'The Women', 'Les femmes', '0', 176),
(5, 'سورة المائدة', 'Al-Maeda', 'The Table Spread', 'La table servie', '0', 120),
(6, 'سورة الأنعام', 'Al-Anaam', 'The cattle', 'Les bestiaux', '0', 165),
(7, 'سورة الأعراف', 'Al-Araf', 'The heights', 'Les murailles', '206', 206),
(8, 'سورة الأنفال', 'Al-Anfal', 'Spoils of war, booty', 'Le butin', '0', 75),
(9, 'سورة التوبة', 'At-Taubah', 'Repentance', 'Le repentir', '0', 129),
(10, 'سورة يونس', 'Yunus', 'Jonah', 'Jonas', '0', 109),
(11, 'سورة هود', 'Hud', 'Hud', 'Hud', '0', 123),
(12, 'سورة يوسف', 'Yusuf', 'Joseph', 'Joseph', '0', 111),
(13, 'سورة الرعد', 'Ar-Rad', 'The Thunder', 'Le tonnerre', '15', 43),
(14, 'سورة إبراهيم', 'Ibrahim', 'Abraham', 'Abraham', '0', 52),
(15, 'سورة الحجر', 'Al-Hijr', 'Stoneland, Rock city, Al-Hijr valley', 'Le chemin rocailleux', '0', 99),
(16, 'سورة النحل', 'An-Nahl', 'The Bee', 'Les abeilles', '50', 128),
(17, 'سورة الإسراء', 'Al-Isra', 'The night journey', 'Le voyage nocturne', '100', 111),
(18, 'سورة الكهف', 'Al-Kahf', 'The cave', 'La caverne', '0', 110),
(19, 'سورة مريم', 'Maryam', 'Mary', 'Marie', '58', 98),
(20, 'سورة طه', 'Taha', 'Ta-Ha', 'Ta-Ha', '0', 135),
(21, 'سورة الأنبياء', 'Al-Anbiya', 'The Prophets', 'Les prophètes', '0', 112),
(22, 'سورة الحج', 'Al-Hajj', 'The Pilgrimage', 'Le pèlerinage', '18', 78),
(23, 'سورة المؤمنون', 'Al-Mumenoon', 'The Believers', 'Les croyants', '0', 118),
(24, 'سورة النور', 'An-Noor', 'The Light', 'La lumière', '0', 64),
(25, 'سورة الفرقان', 'Al-Furqan', 'The Standard', 'Le discernement', '60', 77),
(26, 'سورة الشعراء', 'Ash-Shuara', 'The Poets', 'Les poètes', '0', 227),
(27, 'سورة النمل', 'An-Naml', 'THE ANT', 'Les fourmis', '26', 93),
(28, 'سورة القصص', 'Al-Qasas', 'The Story', 'Le récit', '0', 88),
(29, 'سورة العنكبوت', 'Al-Ankaboot', 'The Spider', 'L’araignée', '0', 69),
(30, 'سورة الروم', 'Ar-Room', 'The Romans', 'Les romains', '0', 60),
(31, 'سورة لقمان', 'Luqman', 'Luqman', 'Luqman', '0', 34),
(32, 'سورة السجدة', 'As-Sajda', 'The Prostration', 'La prosternation', '15', 30),
(33, 'سورة الأحزاب', 'Al-Ahzab', 'The Coalition', 'Les coalisés', '0', 73),
(34, 'سورة سبأ', 'Saba', 'Saba', 'Saba', '0', 54),
(35, 'سورة فاطر', 'Fatir', 'Originator', 'Le créateur', '0', 45),
(36, 'سورة يس', 'Ya Seen', 'Ya Seen', 'Yasîn', '0', 83),
(37, 'سورة الصافات', 'As-Saaffat', 'Those who set the ranks', 'Les rangées', '0', 182),
(38, 'سورة ص', 'Sad', 'Sad', 'La lettre SAD', '24', 88),
(39, 'سورة الزمر', 'Az-Zumar', 'The Troops', 'Les groupes', '0', 75),
(40, 'سورة غافر', 'Ghafir', 'The Forgiver', 'Le pardonneur', '0', 85),
(41, 'سورة فصلت', 'Fussilat', 'Explained in detail', 'Les versets détaillés', '38', 54),
(42, 'سورة الشورى', 'Ash-Shura', 'Council, Consultation', 'La consultation', '0', 53),
(43, 'سورة الزخرف', 'Az-Zukhruf', 'Ornaments of Gold', 'L’ornement', '0', 89),
(44, 'سورة الدخان', 'Ad-Dukhan', 'The Smoke', 'La fumée', '0', 59),
(45, 'سورة الجاثية', 'Al-Jathiya', 'Crouching', 'L’agenouillée', '0', 37),
(46, 'سورة الأحقاف', 'Al-Ahqaf', 'The wind-curved sandhills', 'Les dunes', '0', 35),
(47, 'سورة محمد', 'Muhammad', 'Muhammad', 'Muhammad', '0', 38),
(48, 'سورة الفتح', 'Al-Fath', 'The victory', 'La victoire éclatante', '0', 29),
(49, 'سورة الحجرات', 'Al-Hujraat', 'The private apartments', 'Les appartements', '0', 18),
(50, 'سورة ق', 'Qaf', 'Qaf', 'La lettre QAF', '0', 45),
(51, 'سورة الذاريات', 'Adh-Dhariyat', 'The winnowing winds', 'Qui éparpillent', '0', 60),
(52, 'سورة الطور', 'At-tur', 'Mount Sinai', 'Le Mont Sinaï', '0', 49),
(53, 'سورة النجم', 'An-Najm', 'The Star', 'L’étoile', '62', 62),
(54, 'سورة القمر', 'Al-Qamar', 'The moon', 'La Lune', '0', 55),
(55, 'سورة الرحمن', 'Al-Rahman', 'The Beneficient', 'Le Tout Miséricordieux', '0', 78),
(56, 'سورة الواقعة', 'Al-Waqia', 'The Event, The Inevitable', 'L’événement', '0', 96),
(57, 'سورة الحديد', 'Al-Hadid', 'The Iron', 'Le fer', '0', 29),
(58, 'سورة المجادلة', 'Al-Mujadila', 'She that disputes', 'La discussion', '0', 22),
(59, 'سورة الحشر', 'Al-Hashr', 'Exile', 'L’exode', '0', 24),
(60, 'سورة الممتحنة', 'Al-Mumtahina', 'She that is to be examined', 'L’éprouvée', '0', 13),
(61, 'سورة الصف', 'As-Saff', 'The Ranks', 'Le rang', '0', 14),
(62, 'سورة الجمعة', 'Al-Jumua', 'The congregation, Friday', 'Le vendredi', '0', 11),
(63, 'سورة المنافقون', 'Al-Munafiqoon', 'The Hypocrites', 'Les hypocrites', '0', 11),
(64, 'سورة التغابن', 'At-Taghabun', 'Mutual Disillusion', 'La grande perte', '0', 18),
(65, 'سورة الطلاق', 'At-Talaq', 'Divorce', 'Le divorce', '0', 12),
(66, 'سورة التحريم', 'At-Tahrim', 'Banning', 'L’interdiction', '0', 12),
(67, 'سورة الملك', 'Al-Mulk', 'The Sovereignty', 'La royauté', '0', 30),
(68, 'سورة القلم', 'Al-Qalam', 'The Pen', 'La plume', '0', 52),
(69, 'سورة الحاقة', 'Al-Haaqqa', 'The reality', 'Celle qui montre la vérité', '0', 52),
(70, 'سورة المعارج', 'Al-Maarij', 'The Ascending stairways', 'Les voies d’ascension', '0', 44),
(71, 'سورة نوح', 'Nooh', 'Nooh', 'Noé', '0', 28),
(72, 'سورة الجن', 'Al-Jinn', 'The Jinn', 'Les Djinns', '0', 28),
(73, 'سورة المزمل', 'Al-Muzzammil', 'The enshrouded one', 'L’enveloppé', '0', 20),
(74, 'سورة المدثر', 'Al-Muddathir', 'The cloaked one', 'Le revêtu d’un manteau', '0', 56),
(75, 'سورة القيامة', 'Al-Qiyama', 'The rising of the dead', 'La résurrection', '0', 40),
(76, 'سورة الإنسان', 'Al-Insan', 'The human', 'L’humain', '0', 31),
(77, 'سورة المرسلات', 'Al-Mursalat', 'The emissaries', 'Les envoyés', '0', 50),
(78, 'سورة النبأ', 'An-Naba', 'The tidings', 'La nouvelle', '0', 40),
(79, 'سورة النازعات', 'An-Naziat', 'Those who drag forth', 'Les anges qui arrachent les âmes', '0', 46),
(80, 'سورة عبس', 'Abasa', 'He Frowned', 'Il s’est renfrogné', '0', 42),
(81, 'سورة التكوير', 'At-Takwir', 'The Overthrowing', 'L’obscurcissement', '0', 29),
(82, 'سورة الإنفطار', 'AL-Infitar', 'The Cleaving', 'La rupture', '0', 19),
(83, 'سورة المطففين', 'Al-Mutaffifin', 'Defrauding', 'Les fraudeurs', '0', 36),
(84, 'سورة الانشقاق', 'Al-Inshiqaq', 'The Sundering, Splitting Open', 'La déchirure', '21', 25),
(85, 'سورة البروج', 'Al-Burooj', 'The Mansions of the stars', 'Les constellations', '0', 22),
(86, 'سورة الطارق', 'At-Tariq', 'The morning star', 'L’astre nocturne', '0', 17),
(87, 'سورة الأعلى', 'Al-Ala', 'The Most High', 'Le Très-Haut', '0', 19),
(88, 'سورة الغاشية', 'Al-Ghashiya', 'The Overwhelming', 'L’enveloppante', '0', 26),
(89, 'سورة الفجر', 'Al-Fajr', 'The Dawn', 'L’aube', '0', 30),
(90, 'سورة البلد', 'Al-Balad', 'The City', 'La cité', '0', 20),
(91, 'سورة الشمس', 'Ash-Shams', 'The Sun', 'Le Soleil', '0', 15),
(92, 'سورة الليل', 'Al-Lail', 'The night', 'La nuit', '0', 21),
(93, 'سورة الضحى', 'Ad-Dhuha', 'The morning hours', 'Le jour montant', '0', 11),
(94, 'سورة الشرح', 'Al-Inshirah', 'Solace', 'Réconfort', '0', 8),
(95, 'سورة التين', 'At-Tin', 'The Fig', 'Le figuier', '0', 8),
(96, 'سورة العلق', 'Al-Alaq', 'The Clot', 'L’adhérence', '19', 19),
(97, 'سورة القدر', 'Al-Qadr', 'The Power', 'La destinée', '0', 5),
(98, 'سورة البينة', 'Al-Bayyina', 'The Clear proof', 'La preuve', '0', 8),
(99, 'سورة الزلزلة', 'Al-Zalzala', 'The earthquake', 'La secousse', '0', 8),
(100, 'سورة العاديات', 'Al-Adiyat', 'The Chargers', 'Les coursiers', '0', 11),
(101, 'سورة القارعة', 'Al-Qaria', 'The Calamity', 'Le fracas', '0', 11),
(102, 'سورة التكاثر', 'At-Takathur', 'Competition', 'La course aux richesses', '0', 8),
(103, 'سورة العصر', 'Al-Asr', 'The declining day', 'Le temps', '0', 3),
(104, 'سورة الهمزة', 'Al-Humaza', 'The Traducer', 'Les calomniateurs', '0', 9),
(105, 'سورة الفيل', 'Al-fil', 'The Elephant', 'L’éléphant', '0', 5),
(106, 'سورة قريش', 'Quraish', 'Quraish', 'Coraïsh', '0', 4),
(107, 'سورة الماعون', 'Al-Maun', 'Alms Giving', 'L’ustensile', '0', 7),
(108, 'سورة الكوثر', 'Al-Kauther', 'Abundance', 'L’abondance', '0', 3),
(109, 'سورة الكافرون', 'Al-Kafiroon', 'The Disbelievers', 'Les infidèles', '0', 6),
(110, 'سورة النصر', 'An-Nasr', 'The Succour', 'Les secours', '0', 3),
(111, 'سورة المسد', 'Al-Masadd', 'The Flame', 'Les fibres', '0', 5),
(112, 'سورة الإخلاص', 'Al-Ikhlas', 'Absoluteness', 'Le monothéisme pur', '0', 4),
(113, 'سورة الفلق', 'Al-Falaq', 'The day break', 'L’aube naissante', '0', 5),
(114, 'سورة الناس', 'An-Nas', 'The mankind', 'Les hommes', '0', 6);
