INSERT INTO tags (id, name) VALUES
( 1, "season:winter"),
( 2, "season:spring"),
( 3, "season:summer"),
( 4, "season:autumn"),

( 5, "month:muḥarram"),
( 6, "month:safar"),
( 7, "month:rabii_awal"),
( 8, "month:rabii_thani"),
( 9, "month:jumada_ula"),
(10, "month:jumada_thania"),
(11, "month:rajab"),
(12, "month:shaaban"),
(13, "month:ramadhan"),
(14, "month:shawwal"),
(15, "month:dhul_qaadah"),
(16, "month:dhul_hijjah"),

(17, "weekday:sunday"),
(18, "weekday:monday"),
(19, "weekday:tuesday"),
(20, "weekday:wednesday"),
(21, "weekday:thursday"),
(22, "weekday:friday"),
(23, "weekday:saturday"),

(24, "adhan:before"),
(25, "adhan"),
(26, "adhan:after"),
(27, "prayer:before"),
(28, "prayer:before:fajr"),
(29, "prayer:before:dhuhr"),
(30, "prayer:before:asr"),
(31, "prayer:before:maghrib"),
(32, "prayer:before:isha"),

(33, "iqamah:before"),
(34, "iqamah"),
(35, "iqamah:after"),
(36, "prayer"),
(37, "adhkar"),
(38, "adhkar:fajr"),
(39, "adhkar:dhuhr"),
(40, "adhkar:asr"),
(41, "adhkar:maghrib"),
(42, "adhkar:isha"),

(43, "prayer:after"),
(44, "prayer:after:fajr"),
(45, "prayer:after:dhuhr"),
(46, "prayer:after:asr"),
(47, "prayer:after:maghrib"),
(48, "prayer:after:isha"),

(49, "time:sabah"),
(50, "time:before:sunrise"),
(51, "time:sunrise"),
(52, "time:after:sunrise"),
(53, "time:dhuha"),
(54, "time:hajirah"),
(55, "time:before:zawal"),
(56, "time:masaa"),
(57, "time:before:sunset"),
(58, "time:night:midnight"),
(59, "time:night:last_third"),
(60, "time:night:sahar"),

(61, "event:ashura"),
(62, "event:sacred_month"),
(63, "event:shaaban:mid"),
(64, "event:ramadhan:last_10"),
(65, "event:zakat_fitr"),
(66, "event:eid_fitr"),
(67, "event:dhul_hijjah:first_10"),
(68, "event:arafa"),
(69, "event:eid_adha"),
(70, "event:tashriq"),
(71, "event:rain"),
(72, "event:wind"),

(73, "event:dhul_hijjah:before"),
(74, "event:qarr"),

(75, "event:ayam_bydh");
